### ISSUE TITLE
Heroku won't display links within nav bar that is located in my application.layouts.html.erb

### ISSUE THREAD

**Issue by Alex1100** [Alex1100/museo_lyrics#2]
# HELLLLP! lol

https://serene-anchorage-98234.herokuapp.com/

**Comment by EARnagram** [comment]
Follow the [project issue protocol](https://github.com/ga-students/WDI_DTLA_10/tree/master/projects/project_issues_protocol).

If you need a [good example](https://github.com/Ishmaru/indie_think_tank/issues/2)

Also, please invite all the instructors to be collaborators on your project
