### ISSUE TITLE
Pages on remote heroku site show different content and lack content then on local version of application

### ISSUE THREAD

**Issue by Alex1100** [Alex1100/museo_lyrics#4]
# I have no clue why I am encountering this issue but some of my styling and my like features have basically been ignored when pushing to heroku master... 

I followed protocols from https://devcenter.heroku.com/articles/getting-started-with-rails4 line by line and was quite attentive during jim's lecture, so I have no clue as how I would go about resolving this issue...

Guide me through this beautiful deployment process.

Would I need to use puma gem because of rails assets pipeline having issues or because I need to use a different server to meet environment standards in production vs development??

# LOCAL SONGS/INDEX
<img width="1280" alt="screen shot 2016-06-09 at 10 47 49 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955197/4ede4006-2e94-11e6-8ae6-6642c9237309.png">

# REMOTE SONGS/INDEX
<img width="1280" alt="screen shot 2016-06-09 at 10 47 52 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955205/64da110a-2e94-11e6-80f8-c341fe41fa94.png">

# LOCAL USERS/INDEX
<img width="1280" alt="screen shot 2016-06-09 at 10 49 38 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955221/8ee29d50-2e94-11e6-932d-2c1be07150b6.png">

# REMOTE USERS/INDEX
<img width="1280" alt="screen shot 2016-06-09 at 10 49 42 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955230/9d17bf40-2e94-11e6-9078-2a72df7c3e88.png">

# LOCAL USERS/LIKED_SONGS
<img width="1280" alt="screen shot 2016-06-09 at 10 51 15 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955244/c7e31c74-2e94-11e6-980b-2b54fae0728b.png">

# REMOTE USERS/LIKED_SONGS
<img width="1280" alt="screen shot 2016-06-09 at 10 51 19 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955245/cd10055e-2e94-11e6-8b39-c97c831b1ef1.png">

# LOCAL SONGS/NEW
<img width="1280" alt="screen shot 2016-06-09 at 10 52 43 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955259/edc82f38-2e94-11e6-85ff-b06b41eb1301.png">

# REMOTE SONGS/NEW
<img width="1280" alt="screen shot 2016-06-09 at 10 52 47 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955262/f47ea6d6-2e94-11e6-9128-da6038254a5d.png">

# LOCAL USERS/:ID/EDIT
<img width="1280" alt="screen shot 2016-06-09 at 10 54 02 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955287/21d8a65e-2e95-11e6-8f06-c2a9dad521fb.png">

# REMOTE USERS/:ID/EDIT
<img width="1280" alt="screen shot 2016-06-09 at 10 54 07 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955291/265f03c6-2e95-11e6-9a07-25370b42d84f.png">

# LOCAL /LOGIN
<img width="1280" alt="screen shot 2016-06-09 at 10 55 01 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955305/409898ec-2e95-11e6-97cd-ea51ab37c59d.png">

# REMOTE /LOGIN
<img width="1280" alt="screen shot 2016-06-09 at 10 55 08 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955308/453c08fc-2e95-11e6-8da5-e410c3a1fd0c.png">

# LOCAL USERS/NEW
<img width="1280" alt="screen shot 2016-06-09 at 10 55 42 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955321/5e842f1a-2e95-11e6-96f4-468a83f437af.png">

# REMOTE USERS/NEW
<img width="1280" alt="screen shot 2016-06-09 at 10 55 47 pm" src="https://cloud.githubusercontent.com/assets/14917749/15955327/62e33146-2e95-11e6-83d7-d6201fa10c24.png">

**Comment by jim-clark** [comment]
Bam!
